fixes #10 the menu is now cadetblue when in dev mode
santropolroulant/sous-chef pull request #51
Opened 2021-01-08 19:43 UTC by louhibi

2021-01-08 19:44 UTC, louhibi commented
![image](https://user-images.githubusercontent.com/4096656/104057357-05559e80-51c0-11eb-84a9-a8bf3ceb785e.png)

2021-01-09 00:34 UTC, guillaumep commented on souschef/sous_chef/templates/base.html
> +            <div class="ui left fixed vertical inverted menu {% if SC_ENVIRONMENT_NAME == 'DEV' %}dev-color{% endif %}">
C'est pour staging qu'on veut une couleur distincte.

2021-01-09 00:35 UTC, guillaumep requested changes
.

2021-01-15 00:31 UTC, guillaumep approved these changes
👍

2021-01-15 00:31 UTC, merged